_target_: maniunicon.core.robot.Robot
name: "franka"
robot_interface:
  _target_: maniunicon.robot_interface.franka_fr3_franky.FRANKAInterface
  config:
    urdf_path: "assets/franka_urdf/panda.urdf"
    urdf_package_dirs: ["assets/franka_urdf"]
    num_joints: 6
    init_qpos: [0.0, 0.0, 0.0, -2.2, 0.0, 2.2, 0.7]
    joint_limits:
      min: [-2.8973, -1.7628, -2.8973, -3.0718, -2.8975, -0.0175, -2.91]
      max: [2.8973, 1.7628, 2.8973, -0.0698, 2.8975, 3.7525, 2.91]
    velocity_limits: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]  # rad/s
    torque_limits: [150.0, 150.0, 150.0, 150.0, 150.0, 150.0]  # Nm
    tcp_frame: panda_link7
    # FRANKA-specific configuration
    ip: "172.16.0.2"  # Robot IP address
    lookahead_time: 0.1  # Lookahead time for trajectory following
    gain: 300  # Servo gain
    dt: ${eval:'1 / ${control_frequency}'}  # Control timestep (125Hz)
shared_storage: none # to be replaced
control_frequency: ${control_frequency}
state_update_frequency: ${state_update_frequency}
ee_trans_mat: ${eval:'[[0, -1, 0], [-1, 0, 0], [0, 0, -1]]'}
use_interpolator: false
max_pos_speed: 0.25  # m/s
max_rot_speed: 0.6  # rad/s
warn_on_late: true
synchronized: ${synchronized}

# Workspace bounds for safety constraints
# Set any bound to null to ignore that dimension
workspace_bounds:
  enabled: true
  position:
    x_min: null
    x_max: null
    y_min: null
    y_max: null
    z_min: null
    z_max: null
  orientation:
    x_min: null
    x_max: null
    y_min: null
    y_max: null
    z_min: null
    z_max: null
