_target_: maniunicon.policies.GelloPolicy

device_path: /dev/ttyUSB0
num_joints: ${num_joints}  # Number of robot joints (from default config)
dt: ${eval:'1 / ${policy_frequency}'}  # Time step between actions (seconds)
command_latency: 0.005  # seconds - latency for command execution
synchronized: ${synchronized}

# These parameters are automatically passed by the main system
shared_storage: none  # to be replaced
reset_event: none  # to be replaced 
record_dir: null  # Directory to save recordings (set to path to enable recording)