_target_: maniunicon.policies.SpaceMousePolicy

# SpaceMouse control parameters
translation_scale: ${eval:'0.008 * 30 / ${policy_frequency}'}  # mm - sensitivity for translation movements
rotation_scale: ${eval:'0.5 * 30 / ${policy_frequency}'}  # degrees - sensitivity for rotation movements
control_interval: 1  # Number of action steps to send per update
dt: ${eval:'1 / ${policy_frequency}'}  # Time step between actions (seconds)
command_latency: 0.005  # seconds - latency for command execution
synchronized: ${synchronized}
record_dir: null  # Directory to save recordings (set to path to enable recording)
workspace_bounds: ${robot.workspace_bounds}

# These parameters are automatically passed by the main system
shared_storage: none  # to be replaced
reset_event: none  # to be replaced 